### ISSUE TITLE
Excause me? How do you generate the training dataset ?

### ISSUE THREAD

**Issue by whuwan** [vijaykumar01/stereo_matching#1]
Could you provide how do you generate the training dataset ?

**Comment by mfb999** [comment]
Please post a  method to generate the dataset or a link to download them, thanks.

**Comment by vijaykumar01** [comment]
Kitti2015 dataset is used for training and can be downloaded from http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo

I relied on original below implementation to generate the data set used in training 
https://bitbucket.org/saakuraa/cvpr16_stereo_public

It consists of two steps:
1. Randomly generate locations of left and right patches (37x37) from Kitti2015 train images using preprocess/kitti2015_gene_loc_1.m

2. Extract patches from these locations. (Take a look at DataHandler.lua (next_batch function) to get an idea.)
